name: "Inspect Python code with Pylint"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  check-wrapper:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          path: 'fork_updater'

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Setup dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pylint==2.13.5
          python -m pip install -r requirements.txt
      - name: Run lint check
        run: |
          pylint .
